version: '3.6'
services:
  web:
    image: registry.dis.cwi.nl/traction-mediavault
    ports:
      - "3001:3000"
    command: sh -c "/wait && yarn start"
    environment:
      - WAIT_HOSTS=postgres:5432
      - NODE_ENV=production
      - AWS_CREDENTIAL_FILE_PATH=/run/secrets/aws_credentials
      - ENV_FILE_PATH=/run/secrets/app_env
    secrets:
      - aws_credentials
      - app_env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  postgres:
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=traction
      - POSTGRES_USER=traction
      - POSTGRES_PASSWORD=traction
      - POSTGRES_HOST=postgres
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
volumes:
  pgdata:
secrets:
  aws_credentials:
    external: true
  app_env:
    external: true
