version: '3.6'
services:
  web:
    image: registry.dis.cwi.nl/traction-mediavault
    ports:
      - "80:3000"
    command: sh -c "/wait && yarn start"
    environment:
      - WAIT_HOSTS=postgres:5432
    volumes:
      - /home/ubuntu/containers/web/aws.json:/code/aws.json
      - /home/ubuntu/containers/web/.env:/code/.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
  postgres:
    image: postgres
    volumes:
      - /home/ubuntu/containers/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
