version: "3.6"
services:
  web:
    build: .
    image: registry.dis.cwi.nl/traction-mediavault
    restart: always
    volumes:
      - ./aws.json:/code/aws.json
      - ./.env:/code/.env
      - ./bin:/code/bin
      - ./sequelize:/code/sequelize
      - ./public:/code/public
      - ./views:/code/views
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: sh -c "/wait && yarn start"
    environment:
      - WAIT_HOSTS=postgres:5432
      - POSTGRES_HOST=postgres
      - NODE_ENV=development
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
volumes:
  pgdata:
