name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag traction-mediavault:$(date +%s)
    
    - name: Run linter
      run: docker run -it traction-mediavault:$(date +%s) yarn lint
    
    - name: Run unit tests
      run: docker run -it traction-mediavault:$(date +%s) yarn test
