name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag traction-mediavault:latest

    - name: Run linter
      run: docker run traction-mediavault:latest yarn lint

    - name: Run unit tests
      run: docker run traction-mediavault:latest yarn test
