name: Build and test

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Install dependencies, lint code and run tests
    runs-on: ubuntu-18.04
    env:
      IMAGE_NAME: traction-mediavault
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Run unit tests
        run: yarn test
